### ISSUE TITLE
Page keep showing "loading...", not showing any useful information

### ISSUE THREAD

**Issue by gwjwin** [dvestezar/JB_WebBased_OpenVPN_Monitor#2]
I tried DEMO on http://ovpnmonitor.dvestezar.cz/mon/ and put all files into my apache server, but both are showing "loading..." all the time, cannot click and not showing any useful information. (I've edited the config.php management port)

AND on my server also shows some Notice, but I think it's not important:
Notice: Undefined index: s in ./lib/php/class/html_class.php on line 100
Notice: Undefined variable: cmd in ./index.php on line 14

I'm using Chrome. Is that ok? Someone can help me? Thanks.

**Comment by dvestezar** [comment]
I' so sorry. I forgot for changes in JavaScriptAjaxTable - "Q" like shorcut to jQuery. This fix is tested in online demo, and yes I forgot to update changes JavaScriptAjaxTable on Github. Try it

**Comment by gwjwin** [comment]
It works now, thanks!
The only problem now is the website need to load external css/js files on www.dvestezar.cz/!moje_js/ , which may be a problem on a workstation without internet access. But it's ok for me. Thank again.

**Comment by dvestezar** [comment]
You can use same file/s from repositories and rewrite links to local place as your choise. Dvestezar.cz is place with newest version whitch will be copied to repositories.

Odesláno ze Samsung Mobile

-------- Původní zpráva --------
Od: gwjwin notifications@github.com 
Datum:28. 02. 2015  17:08  (GMT+01:00) 
Komu: dvestezar/JB_WebBased_OpenVPN_Monitor JB_WebBased_OpenVPN_Monitor@noreply.github.com 
Cc: John info@dvestezar.cz 
Předmět: Re: [JB_WebBased_OpenVPN_Monitor] Page keep showing "loading...", not
  showing any useful information (#2) 

It works now, thanks!
The only problem now is the website need to load external css/js files on www.dvestezar.cz/!moje_js/ , which may be a problem on a workstation without internet access. But it's ok for me. Thank again.
